#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/parse-preset.sh" "$@"
mkdir -p "$CCACHE_TEMPDIR"

FILTER_CHAIN_BUILD_TYPE=Debug
FILTER_CHAIN_ENABLE_ASAN=OFF
FILTER_CHAIN_ENABLE_UBSAN=OFF
FILTER_CHAIN_ENABLE_CLANG_TIDY=OFF
FILTER_CHAIN_ENABLE_PROFILING=OFF

case "$PRESET" in
  debug)
    FILTER_CHAIN_BUILD_TYPE=Debug
    ;;
  release)
    FILTER_CHAIN_BUILD_TYPE=Release
    ;;
  relwithdebinfo)
    FILTER_CHAIN_BUILD_TYPE=RelWithDebInfo
    ;;
  asan)
    FILTER_CHAIN_ENABLE_ASAN=ON
    ;;
  ubsan)
    FILTER_CHAIN_ENABLE_UBSAN=ON
    ;;
  asan-ubsan)
    FILTER_CHAIN_ENABLE_ASAN=ON
    FILTER_CHAIN_ENABLE_UBSAN=ON
    ;;
  test)
    FILTER_CHAIN_ENABLE_ASAN=ON
    FILTER_CHAIN_ENABLE_CLANG_TIDY=ON
    ;;
  quality)
    FILTER_CHAIN_ENABLE_ASAN=ON
    FILTER_CHAIN_ENABLE_CLANG_TIDY=ON
    ;;
  profile)
    FILTER_CHAIN_BUILD_TYPE=Release
    FILTER_CHAIN_ENABLE_PROFILING=ON
    ;;
esac

FILTER_CHAIN_BUILD_DIR="build/filter-chain-package/$PRESET"
FILTER_CHAIN_INSTALL_DIR="$(pwd)/build/filter-chain-install/$PRESET"
rm -rf "$FILTER_CHAIN_INSTALL_DIR"
cmake -S filter-chain -B "$FILTER_CHAIN_BUILD_DIR" \
  -DCMAKE_BUILD_TYPE="$FILTER_CHAIN_BUILD_TYPE" \
  -DCMAKE_CXX_STANDARD=20 \
  -DCMAKE_CXX_STANDARD_REQUIRED=ON \
  -DCMAKE_CXX_EXTENSIONS=OFF \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DFILTER_CHAIN_LIBRARY_TYPE=STATIC \
  -DFILTER_CHAIN_BUILD_TESTS=OFF \
  -DENABLE_ASAN="$FILTER_CHAIN_ENABLE_ASAN" \
  -DENABLE_UBSAN="$FILTER_CHAIN_ENABLE_UBSAN" \
  -DENABLE_CLANG_TIDY="$FILTER_CHAIN_ENABLE_CLANG_TIDY" \
  -DENABLE_PROFILING="$FILTER_CHAIN_ENABLE_PROFILING"
cmake --build "$FILTER_CHAIN_BUILD_DIR"
cmake --install "$FILTER_CHAIN_BUILD_DIR" --prefix "$FILTER_CHAIN_INSTALL_DIR"

cmake --preset "$PRESET"
cmake --build --preset "$PRESET"
